### ISSUE TITLE
Accentuated characters do not appear on the website...

### ISSUE THREAD

**Issue by caroapp** [tjmonsi/chi2016-program#1]
...which is a bit too bad for an international conference.

**Comment by tjmonsi** [comment]
We're fixing it as of now :)

**Comment by tjmonsi** [comment]
The guys at the program fixed the texts already and it should be showing the right characters now. It seems we just encoded it directly to UTF-8 instead of using the right encoding scheme. Hopefully it's ok also on your side. Please do let us know if we have missed something. I'm closing this issue for now :)

**Comment by caroapp** [comment]
It doesn't appear as fixed on the website (https://chi2016.acm.org/program/?tab=chi2016-schedule). For example, "María Jesús Lobo" is "Mara-Jess Lobo" or "Rafael Morales González" is "Rafael Morales Gonzlez" ...

**Comment by tjmonsi** [comment]
Hi caroline,

So it seems. I'll notify the ones who are handling Cobi. But i'll do a pass
on the original csv later and switch the program from utf8 to another codec

**Comment by tjmonsi** [comment]
I have fixed it :) But the Confer database (Alternative Full Schedule) will have a different data (I only have access to CHI 2016 database). I'm going to tell them though
