### ISSUE TITLE
Characters with accents are missing, causing authors' names to be misspelled

### ISSUE THREAD

**Issue by ignacioxd** [tjmonsi/chi2016-program#3]
This is mostly an issue with names in Spanish. I've found at least four instances: Domínguez, Rodríguez, González, and López.

Some affected papers:
* Breaking the UCD process: The case study of a failed Mexican Government project.
* The Mimesis Effect: The Effect of Roles on Player Choice in Interactive Narrative Role-Playing Games
* TouchTokens: Guiding Touch Patterns with Passive Tokens

**Comment by tjmonsi** [comment]
Hi @ignacioxd 

I just fixed it now. :) It is because of the UTF 8 encoding. But I only have access to the CHI 2016 database and not Confer database (Alternative Schedule view). I'm going to contact them on this though. 

If there's anything that I have missed, please let me know. If not, please feel free to close this issue

**Comment by ignacioxd** [comment]
Looks great! Thanks for the quick fix.
